### PR TITLE
Fixed PacMan, Ghost, and Map move() functions.

### PR DESCRIPTION
**Pull request by jmablanco**
This should fix the move() functions, but tests aren't passing yet because other functions being used in the move() tests haven't been fixed yet.

### CODE REVIEW

**Review by ggarcz1 — COMMENTED** [review]
I think the PacMan fix doesn't pass the tests.  The other two seem to work however

**Comment by jmablanco** [comment]
PacMan.move() should pass the tests now, lemme run the workflow really quick @ggarcz1 

EDIT: Still failing, but I think it's due to get_valid_moves being incorrect in fix-jmablanco, I'm not sure why TestGhostMove is passing but it is but once this gets merged to FTR-Fix, it should pass once get_valid_moves() is fixed. Everything in PacMan.move() should be correct though!

**Comment by ggarcz1** [comment]
yep just discovered thats what it was!

**Review by ggarcz1 — APPROVED** [review]
molto bene!

**Pull request merged**
